---
title: "Family Guy"
author: "Isioma Mabatah"
date: "8/14/2021"
output: 
  html_document:
    theme: lumen
    toc: true
    toc_float: true
    code_folding: hide
---

# Summary

## Libraries

```{r library, message=FALSE, warning=FALSE, echo=TRUE}
library(tidyverse)
library(forcats)
theme_set(theme_minimal())
library(tidytext)
library(RColorBrewer)
library(grid)
library(magick)
library(cowplot)
library(ggpubr)
```

## Data

```{r data, message=FALSE, warning=FALSE, echo=TRUE}
# Load Data
family_raw <- read_csv("Data/Family_guy_dialog.csv")

# Feature processing & cleaing
family <- family_raw %>% 
  mutate(index = row_number()) %>% 
  select(index, season = seasons, character, dialog) %>% 
  mutate(season = str_replace(season, "season", "") %>% as.integer %>% as.factor) %>% 
  filter(character != "Maids and Butlers M&B")
```

```{r palatte}
# color palette
peter <- "#2A6431"
lois <- "#F8784E"
stewie <- "#EB0C42"
brian <- "#E1E0DE"
chris <- "#0576C2"
meg <- "#E06EAA"
quagmire <- "#FAEE40"
cleveland <- "#783204"

family_guy_Palette <- c(brian,chris,cleveland,lois,meg,peter,quagmire,stewie)
```


# Exploratory Data Analysis

```{r count_Season}
family %>% count(season) %>% 
  knitr::kable(caption = "Season: Line Count")
```

```{r count_Character}
family %>% count(character) %>% arrange(-n) %>% 
  knitr::kable(caption = "Character: Line Count")
```

```{r counts, message=FALSE, echo=TRUE, fig.align='center', fig.height=8, fig.width=10}
# EDA
family %>% 
  count(season, character) %>% 
  ggplot(aes(fct_reorder(character, n), n, fill = character)) + 
  geom_col(show.legend = FALSE, alpha = 0.4) +
  geom_label(aes(label = n), size = 3, color = "white") +
  facet_wrap(~season, scales = "free_x", nrow = 3) +
  coord_flip() +
  labs(title = "Family Guy: Line Count") +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    axis.title = element_blank(),
    axis.text.y = element_text(face = "bold"),
    axis.text.x = element_blank(),
    strip.text = element_text(face = "bold", size = 15, color = "grey35"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = family_guy_Palette)
```

## Text Preprocessing

### Term Frequency [TABS] {.tabset .tabset-fade}

```{r tf, message=FALSE, echo=TRUE}
# Bag of Words
family_tidy <- family %>% 
  unnest_tokens(word, dialog) %>% 
  anti_join(stop_words)

# Term Frequency
family_tf <- family_tidy %>% 
  count(word) %>% 
  arrange(-n)

family_tf %>% 
  top_n(25, n) %>% 
  knitr::kable(caption = "Term Frequency: Top 25")
```

#### By Character

```{r tf_Character, echo=TRUE, fig.align='center', fig.height=8, fig.width=10}

# Top Words (Character)
family_tidy %>% 
  group_by(character) %>%
  count(word) %>% 
  arrange(-n) %>% 
  top_n(3, n) %>% 
  ggplot(aes(n, fct_reorder(word,n), fill = character)) +
  geom_col(show.legend = FALSE, alpha = 0.4) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~character, scales = "free") +
  labs(title = "Term Frequency: Top 5",
       x = NULL, y = NULL) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    axis.title = element_blank(),
    axis.text.y = element_text(face = "bold"),
    axis.text.x = element_blank(),
    strip.text = element_text(face = "bold", size = 15, color = "grey35"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = family_guy_Palette)
```

#### By Season

```{r tf_Season, echo=TRUE, fig.align='center', fig.height=8, fig.width=10}
# Top Words (Season 1-6)
family_tidy %>% 
  filter(season %in% 1:6) %>% 
  group_by(character) %>%
  count(word) %>% 
  arrange(-n) %>% 
  top_n(4, n) %>% 
  ggplot(aes(n, fct_reorder(word,n), fill = character)) +
  geom_col(show.legend = FALSE, alpha = 0.4) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~character, scales = "free") +
  labs(
    title = "Term Frequency: Top 5",
    subtitle = "Season: 1-6",
    x = NULL, y = NULL
  ) +
 theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.text.y = element_text(face = "bold"),
    axis.text.x = element_blank(),
    strip.text = element_text(face = "bold", size = 15, color = "grey35"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = family_guy_Palette)


# Top Words (Season 6-12)
family_tidy %>% 
  filter(season %in% 6:12) %>% 
  group_by(character) %>%
  count(word) %>% 
  arrange(-n) %>% 
  top_n(5, n) %>% 
  ggplot(aes(n, fct_reorder(word,n), fill = character)) +
  geom_col(show.legend = FALSE, alpha = 0.4) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~character, scales = "free") +
  labs(
    title = "Term Frequency: Top 5",
    subtitle = "Season: 6-12",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.text.y = element_text(face = "bold"),
    axis.text.x = element_blank(),
    strip.text = element_text(face = "bold", size = 15, color = "grey35"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = family_guy_Palette)
```

#### Bigram

```{r bigram, message=FALSE, echo=TRUE}
# Bigram
family_bigram <- family %>% 
  unnest_tokens(bigram, dialog,
                token = "ngrams",
                n = 2)
family_bigram_clean_seperate <- family_bigram %>% 
  separate(bigram, c("word1","word2"), sep = " ") %>% 
  filter(!word1 %in% stop_words$word) %>% 
  filter(!word2 %in% stop_words$word)

family_bigram_clean_unite <- 
  family_bigram_clean_seperate %>% 
  unite(bigram, word1, word2, sep = " ") %>% 
  filter(bigram != "NA NA")

family_bigram_clean_unite %>% count(bigram) %>% arrange(-n) %>% top_n(25, n) %>% 
  knitr::kable(caption = "Bigram: Top 25")

# Top Bigram: Popular Words (Character)
family_bigram_clean_unite %>% 
  group_by(character) %>%
  count(bigram) %>% 
  arrange(-n) %>% 
  top_n(5, n) %>% 
  ggplot(aes(n, fct_reorder(bigram,n), fill = character)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~character, scales = "free") +
  labs(title = "Top Bigram") +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.3, size = 20),
    axis.title = element_blank(),
    axis.text.y = element_text(face = "bold")
  ) +
  scale_fill_manual(values = family_guy_Palette)

# Top Bigram: (Season 1-6)
family_bigram_clean_unite %>% 
  group_by(character) %>%
  count(bigram) %>% 
  arrange(-n) %>% 
  top_n(3, n) %>% 
  ungroup() %>% 
  ggplot(aes(n, fct_reorder(bigram,n), fill = character)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~character, scales = "free") +
  labs(
    title = "Top Bigrams",
    subtitle = "Season: ALL",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.3, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.3, size = 15),
    axis.title = element_blank(),
    axis.text.y = element_text(face = "bold")
  ) +
  scale_fill_manual(values = family_guy_Palette)

```

# Sentiment Analysis [TABS] {.tabset .tabset-fade}

## BING

```{r bing, message=FALSE, warning=FALSE, echo=TRUE}
family_bing <- family_tidy %>% inner_join(get_sentiments("bing"))
family_bing %>% count(sentiment)
```

```{r bing_polarity, message=FALSE, echo=TRUE, fig.align='center', fig.height=3, fig.width=10}
# By Index
family_bing %>% 
  count(index, season, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(polarity = positive - negative) %>% 
  ggplot(aes(index, polarity)) +
  geom_smooth(show.legend = FALSE) +
  geom_hline(yintercept = 0, color = "red") +
  labs(
    title = "Polarity",
    y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold", size = 10)
  )

# By season
family_bing %>% 
  count(index, season, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(polarity = positive - negative) %>% 
  ggplot(aes(index, polarity)) +
  geom_smooth(show.legend = FALSE) +
  geom_hline(yintercept = 0, color = "red") +
  facet_wrap(~season, scales = "free_x", nrow = 2) +
  labs(
    title = "Polarity",
    subtitle = "By Season",
    y = NULL
  ) + 
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold", size = 10)
  )

```

```{r bing_polarity_Character, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=5, fig.width=8}
# By Character
# - Peter
gg_Polarity_Peter <- family_bing %>%
  filter(character == "Peter") %>% 
  count(index, season, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(polarity = positive - negative) %>% 
  ggplot(aes(index, polarity)) +
  geom_smooth(show.legend = FALSE, size = 1, color = peter) +
  geom_hline(yintercept = 0, color = "red", linetype = 2, alpha = 0.3) +
  facet_wrap(~season, scales = "free_x", nrow = 1) +
  labs(title = "Polarity throughout the Series",
       subtitle = "Peter",
       x = "Season", y = NULL) +
  theme_minimal() +
    theme(
      plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 12),
      plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 6),
      axis.title.x = element_text(face = "bold", size = 10),
      axis.text.x = element_blank() 
)
# - Lois
gg_Polarity_Lois <- family_bing %>%
    filter(character == "Lois") %>% 
    count(index, season, sentiment) %>% 
    spread(sentiment, n, fill = 0) %>% 
    mutate(polarity = positive - negative) %>% 
    ggplot(aes(index, polarity)) +
    geom_smooth(show.legend = FALSE, size = 1, color = lois) +
    geom_hline(yintercept = 0, color = "red", linetype = 2, alpha = 0.3) +
    facet_wrap(~season, scales = "free_x", nrow = 1) +
    labs(title = "Polarity throughout the Series",
         subtitle = "Lois",
         x = NULL, y = NULL) +
    theme_minimal() +
      theme(
        plot.title = element_blank(),
        plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 10),
        axis.title.x = element_text(face = "bold", size = 6),
        axis.text.x = element_blank() 
      )
# - Stewie
gg_Polarity_Stewie <- family_bing %>%
    filter(character == "Stewie") %>% 
    count(index, season, sentiment) %>% 
    spread(sentiment, n, fill = 0) %>% 
    mutate(polarity = positive - negative) %>% 
    ggplot(aes(index, polarity)) +
    geom_smooth(show.legend = FALSE, size = 1, color = stewie) +
    geom_hline(yintercept = 0, color = "red", linetype = 2, alpha = 0.3) +
    facet_wrap(~season, scales = "free_x", nrow = 1) +
    labs(title = "Polarity throughout the Series",
         subtitle = "Stewie",
         x = NULL, y = NULL) +
    theme_minimal() +
      theme(
        plot.title = element_blank(),
        plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 10),
        axis.title.x = element_text(face = "bold", size = 10),
        axis.text.x = element_blank() 
      )
# - Brian
gg_Polarity_Brian <- family_bing %>%
    filter(character == "Brian") %>% 
    count(index, season, sentiment) %>% 
    spread(sentiment, n, fill = 0) %>% 
    mutate(polarity = positive - negative) %>% 
    ggplot(aes(index, polarity)) +
    geom_smooth(show.legend = FALSE, size = 1, color = brian) +
    geom_hline(yintercept = 0, color = "red", linetype = 2, alpha = 0.3) +
    facet_wrap(~season, scales = "free_x", nrow = 1) +
    labs(title = "Polarity throughout the Series",
         subtitle = "Brian",
         x = NULL, y = NULL) +
    theme_minimal() +
      theme(
        plot.title = element_blank(),
        plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 10),
        axis.title.x = element_text(face = "bold", size = 10),
        axis.text.x = element_blank() 
      )
# - Chris
gg_Polarity_Chris <- family_bing %>%
    filter(character == "Chris") %>% 
    count(index, season, sentiment) %>% 
    spread(sentiment, n, fill = 0) %>% 
    mutate(polarity = positive - negative) %>% 
    ggplot(aes(index, polarity)) +
    geom_smooth(show.legend = FALSE, size = 1, color = chris) +
    geom_hline(yintercept = 0, color = "red", linetype = 2, alpha = 0.3) +
    facet_wrap(~season, scales = "free_x", nrow = 1) +
    labs(title = "Polarity throughout the Series",
         subtitle = "Chris",
         x = NULL, y = NULL) +
    theme_minimal() +
      theme(
        plot.title = element_blank(),
        plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 10),
        axis.title.x = element_text(face = "bold", size = 10),
        axis.text.x = element_blank() 
      )
# - Meg
gg_Polarity_Meg <- family_bing %>%
    filter(character == "Meg") %>% 
    count(index, season, sentiment) %>% 
    spread(sentiment, n, fill = 0) %>% 
    mutate(polarity = positive - negative) %>% 
    ggplot(aes(index, polarity)) +
    geom_smooth(show.legend = FALSE, size = 1, color = meg) +
    geom_hline(yintercept = 0, color = "red", linetype = 2, alpha = 0.3) +
    facet_wrap(~season, scales = "free_x", nrow = 1) +
    labs(title = "Polarity throughout the Series",
         subtitle = "Meg",
         x = NULL, y = NULL) +
    theme_minimal() +
      theme(
        plot.title = element_blank(),
        plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 10),
        axis.title.x = element_text(face = "bold", size = 10),
        axis.text.x = element_blank() 
      )

# Visual
ggarrange(gg_Polarity_Peter,gg_Polarity_Lois, gg_Polarity_Stewie,
          ncol = 1)
ggarrange(gg_Polarity_Brian, gg_Polarity_Chris, gg_Polarity_Meg, 
          ncol = 1)
```

```{r bing_words_All, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=8, fig.width=10}
family_bing %>% 
  count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(polarity = positive - negative) %>% 
  mutate(pos_neg = ifelse(polarity > 0, "positive","negative")) %>% 
  filter(abs(polarity) >= 8) %>% 
  ggplot(aes(fct_reorder(word, polarity), polarity, fill = pos_neg)) +
  geom_col(show.legend = FALSE) +
  geom_label(aes(label = polarity), color = "white") +
  coord_flip() +
  labs(title = "Polarity of Words",
       subtitle = "Series: ALL",
       x = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold", size = 10),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("tomato", "forestgreen"))
```

```{r bing_polarity_Season, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=1, fig.width=12}
family_bing %>% 
  group_by(season) %>% 
  count(sentiment) %>% 
  ggplot(aes(sentiment,n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~season, nrow = 1) +
  theme_bw() +
  labs(
    title = "Polarity by Season",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold", size = 10),
    axis.text.x = element_blank(),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("tomato","forestgreen"))

# Dataframe
family_bing %>% 
  count(season, sentiment) %>% 
  spread(sentiment, n) %>% 
  mutate(overall = positive - negative)
```

```{r bing_polarity_words_Season, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=6, fig.width=8}
# Season: 1-6
family_bing %>% 
  filter(season %in% 1:6) %>% 
  group_by(sentiment) %>% 
  count(word, sort = TRUE) %>%
  top_n(10, n) %>%
  ggplot(aes(n, fct_reorder(word, n), fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free") +
  theme_bw() +
  labs(
    title = "Polarity: Top Words",
    subtitle = "Season: 1-6",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold", size = 10)
  )

# Season: 7-12
family_bing %>% 
  filter(season %in% 7:12) %>% 
  group_by(sentiment) %>% 
  count(word, sort = TRUE) %>%
  top_n(10, n) %>%
  ggplot(aes(n, fct_reorder(word, n), fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free") +
  theme_bw() +
  labs(
    title = "Polarity: Top Words",
    subtitle = "Season: 7-12",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold", size = 10)
  )
```

```{r bing_polarity_words_Character, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=3, fig.width=12}
# Total by Character
family_bing %>% 
  group_by(character) %>% 
  count(sentiment) %>% 
  ggplot(aes(sentiment, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~character, nrow = 1) +
  labs(
    title = "Polarity by Character",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.title.x = element_text(face = "bold", size = 10),
    axis.text = element_blank(),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("tomato","forestgreen"))
```

```{r bing_polarity_per_Season, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=4, fig.width=12}
# % Polarity by Season
family_bing %>% 
  count(season, character, sentiment) %>% 
  ggplot(aes(character, n, fill = sentiment)) +
  geom_col(position = "fill", alpha = 0.5, show.legend = FALSE) +
  facet_wrap(~ season, scales = "free_x", nrow = 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "% Polarity of Characters by Season",
       x = NULL, y = NULL) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.text.y = element_blank(),
    axis.text.x = element_text(face = "italic", size = 7, vjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("tomato","forestgreen"))
```

```{r bing_character_top_words, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=8, fig.width=10}
# Character Top Words: Positive
family_bing %>%
  filter(sentiment == "positive") %>% 
  group_by(character) %>% 
  count(word) %>% 
  top_n(3, n) %>% 
  ungroup() %>% 
  ggplot(aes(n, fct_reorder(word, n), fill = character)) +
  geom_col(show.legend = FALSE, alpha = 0.5) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~ character, scales = "free", nrow = 2) +
  labs(
    title = "Top Words",
    subtitle = "Positive",
    x = NULL, y = NULL
  ) +
  theme(
      plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
      plot.subtitle = element_text(color = "forestgreen", hjust = 0.5, size = 15),
      axis.text.x = element_blank(),
      strip.text = element_text(face = "bold", size = 15, color = "grey35"),
      legend.position = "none"
  ) +
  scale_fill_manual(values = family_guy_Palette)

# Character Top Words: Negative
family_bing %>%
  filter(sentiment == "negative") %>% 
  group_by(character) %>% 
  count(word) %>% 
  top_n(3, n) %>% 
  ungroup() %>% 
  ggplot(aes(n, fct_reorder(word, n), fill = character)) +
  geom_col(show.legend = FALSE, alpha = 0.5) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~ character, scales = "free", nrow = 2) +
  labs(
    title = "Top Words",
    subtitle = "Negative",
    x = NULL, y = NULL
  ) +
  theme(
      plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
      plot.subtitle = element_text(color = "tomato", hjust = 0.5, size = 15),
      axis.text.x = element_blank(),
      strip.text = element_text(face = "bold", size = 15, color = "grey35"),
      legend.position = "none"
  ) +
  scale_fill_manual(values = family_guy_Palette)
```

```{r bing_character_top_words_Season, message=FALSE, warning=FALSE, echo=TRUE, fig.align='center', fig.height=8, fig.width=10}
# Season 1-6
family_bing %>% 
  filter(season %in% 1:6) %>% 
  group_by(character) %>% 
  count(sentiment, word) %>% 
  top_n(5, n) %>% 
  ungroup() %>% 
  ggplot(aes(n, fct_reorder(word, n), fill = sentiment)) +
  geom_col(show.legend = FALSE, alpha = 0.3) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~ character, scales = "free", nrow = 2) +
  labs(
    title = "Top Words by Character",
    subtitle = "Season: 1-6",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.text.x = element_blank(),
    strip.text = element_text(face = "bold", size = 15, color = "grey35"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("tomato","forestgreen"))

# Season 6-12
family_bing %>% 
  filter(season %in% 7:12) %>% 
  group_by(character) %>% 
  count(sentiment, word) %>% 
  top_n(5, n) %>% 
  ungroup() %>% 
  ggplot(aes(n, fct_reorder(word, n), fill = sentiment)) +
  geom_col(show.legend = FALSE, alpha = 0.3) +
  geom_label(aes(label = n), color = "white") +
  facet_wrap(~ character, scales = "free", nrow = 2) +
  labs(
    title = "Top Words by Character",
    subtitle = "Season: 7-12",
    x = NULL, y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", color = "#2A2A57", hjust = 0.5, size = 20),
    plot.subtitle = element_text(color = "darkgoldenrod", hjust = 0.5, size = 15),
    axis.text.x = element_blank(),
    strip.text = element_text(face = "bold", size = 15, color = "grey35"),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("tomato","forestgreen"))
```

## NRC

## AFINN

# Topic Modeling

END - Sentiment Analysis TABS - END